<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button-downloadcontract</name>
   <tag></tag>
   <elementGuidId>3c6a263a-dbf1-42fa-810e-908c1ee5f040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href='https://ut-staging.bgskr-project.my.id/uploads/project/formContract/FRC_2024MB01320230327.xlsx']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
