<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>home-page</name>
   <tag></tag>
   <elementGuidId>aa13dfaf-2b3f-4442-8aae-60da1f28ab7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/div[2]/div/a[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;__layout&quot;)/div[@class=&quot;font-mont bg-gry-light min-h-screen&quot;]/div[1]/div[@class=&quot;bg-white pt-5&quot;]/div[@class=&quot;container mx-auto uppercase flex justify-center py-1&quot;]/a[@class=&quot;ml-4 px-3 py-1 text-sm font-medium text-blk-light focus:outline-none&quot;][count(. | //*[@href = '/tender' and (text() = 'Tender' or . = 'Tender')]) = count(//*[@href = '/tender' and (text() = 'Tender' or . = 'Tender')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9d48d18f-b65c-45f5-a333-f27bdd9ed252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tender</value>
      <webElementGuid>a4d0e582-5b53-43a8-afe8-e1000f3dbc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-4 px-3 py-1 text-sm font-medium text-blk-light focus:outline-none</value>
      <webElementGuid>a6a8e79e-457b-4694-9a7b-43bbd3ff4a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tender</value>
      <webElementGuid>aafe2e23-a004-494b-88ea-f7da45c5a239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;font-mont bg-gry-light min-h-screen&quot;]/div[1]/div[@class=&quot;bg-white pt-5&quot;]/div[@class=&quot;container mx-auto uppercase flex justify-center py-1&quot;]/a[@class=&quot;ml-4 px-3 py-1 text-sm font-medium text-blk-light focus:outline-none&quot;]</value>
      <webElementGuid>2f229346-5c09-426e-b115-9d7630e8e520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div[2]/div/a[5]</value>
      <webElementGuid>696b9f39-af22-4b59-80e8-a1c30dc7571b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tender')]</value>
      <webElementGuid>9fc1052b-ee2a-4b77-9647-c3be2399a740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design &amp; Development'])[1]/following::a[1]</value>
      <webElementGuid>815b8417-907d-4b31-b1cf-766a9d7da041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Request'])[1]/following::a[2]</value>
      <webElementGuid>658e7171-1769-4c98-8d78-55f942ba0185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contracts'])[1]/preceding::a[1]</value>
      <webElementGuid>ac062828-acb7-4b36-9ba3-7b5a32ea1009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring'])[1]/preceding::a[2]</value>
      <webElementGuid>5da67210-fb11-4bf6-8acc-2fe5a716cfd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tender']/parent::*</value>
      <webElementGuid>46159db1-90f4-4bfd-9bbb-c54bff8cd62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tender')]</value>
      <webElementGuid>0c1d9f87-dee4-42f8-acfe-02789709d19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>afb5c704-b9e8-4eab-8704-6ca1bde8647f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tender' and (text() = 'Tender' or . = 'Tender')]</value>
      <webElementGuid>2d0240ce-56ed-4d97-839a-04c733bed694</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
